<?php

namespace Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Fixture;

/**
 * This a complete file
 *
 * @property bool $Boolean
 * @property float $Currency
 * @property ?string $Date
 * @property float $Decimal
 * @property ?string $Enum
 * @property ?string $HTMLText
 * @property ?string $HTMLVarchar
 * @property int $Int
 * @property float $Percentage
 * @property ?string $Datetime
 * @property ?string $Text
 * @property ?string $Time
 * @property ?string $Varchar
 * @property int $BelongsToRelationshipID
 * @method \Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Source\RelationMock BelongsToRelationship()
 * @property int $HasOneRelationshipID
 * @method \Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Source\RelationMock HasOneRelationship()
 * @method \SilverStripe\ORM\HasManyList|\Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Source\RelationMock[] HasManyRelationship()
 * @method \SilverStripe\ORM\ManyManyList|\Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Source\RelationMock[] BelongsManyManyRelationship()
 * @method \SilverStripe\ORM\ManyManyList|\Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Source\RelationMock[] ManyManyRelationship()
 * @method \SilverStripe\ORM\ManyManyThroughList|\Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Source\RelationMock[] ManyManyThroughRelationship()
 * @mixin \Cambis\SilverstripeRector\Tests\Set\Silverstripe413\Source\ExtensionMock
 */
class DataObjectComplete extends \SilverStripe\ORM\DataObject implements \SilverStripe\Dev\TestOnly
{
}
