<?php
namespace SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToExtensionRector\FixtureIntersection;

/**
 * @extends \SilverStripe\Core\Extension<\SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToExtensionRector\Source\OwnerMockOne&static>
 */
class HasOneOwnerComplete extends \SilverStripe\Core\Extension implements \SilverStripe\Dev\TestOnly
{
}
