<?php

namespace Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Fixture;

class DataExtension extends \SilverStripe\ORM\DataExtension implements \SilverStripe\Dev\TestOnly
{
}

?>
-----
<?php

namespace Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Fixture;

/**
 * @property bool $Boolean
 * @property float $Currency
 * @property ?string $Date
 * @property float $Decimal
 * @property ?string $Enum
 * @property ?string $HTMLText
 * @property ?string $HTMLVarchar
 * @property int $Int
 * @property float $Percentage
 * @property ?string $Datetime
 * @property ?string $Text
 * @property ?string $Time
 * @property ?string $Varchar
 * @property int $BelongsToRelationshipID
 * @method \Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Source\RelationMock BelongsToRelationship()
 * @property int $HasOneRelationshipID
 * @method \Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Source\RelationMock HasOneRelationship()
 * @method \SilverStripe\ORM\HasManyList<\Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Source\RelationMock> HasManyRelationship()
 * @method \SilverStripe\ORM\ManyManyList<\Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Source\RelationMock> BelongsManyManyRelationship()
 * @method \SilverStripe\ORM\ManyManyList<\Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Source\RelationMock> ManyManyRelationship()
 * @method \SilverStripe\ORM\ManyManyThroughList<\Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Source\RelationMock> ManyManyThroughRelationship()
 * @extends \SilverStripe\ORM\DataExtension<(\Cambis\SilverstripeRector\Tests\Set\Silverstripe52\Source\RelationMock & static)>
 */
class DataExtension extends \SilverStripe\ORM\DataExtension implements \SilverStripe\Dev\TestOnly
{
}

?>