<?php
namespace Cambis\SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToExtensionRector\FixtureUnion;

/**
 * @extends \SilverStripe\Core\Extension<\Cambis\SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToExtensionRector\Source\OwnerMockOne | static>
 */
class HasOneOwnerComplete extends \SilverStripe\Core\Extension implements \SilverStripe\Dev\TestOnly
{
}
