<?php

namespace SilverstripeRector\Tests\Silverstripe413\Rector\Class_\AddBelongsManyManyMethodAnnotationsToDataObjectRector\Fixture;

/**
 * @method \SilverStripe\ORM\ManyManyList|\SilverstripeRector\Tests\Silverstripe413\Rector\Class_\AddBelongsManyManyMethodAnnotationsToDataObjectRector\Source\RelationMock[] BelongsManyManyRelationship()
 */
class BelongsManyManyComplete extends \SilverStripe\ORM\DataObject implements \SilverStripe\Dev\TestOnly
{
}
