<?php

namespace SilverstripeRector\Tests\Silverstripe413\Rector\Class_\AddManyManyMethodAnnotationsToDataObjectRector\Fixture;

/**
 * @method \SilverStripe\ORM\ManyManyList|\SilverstripeRector\Tests\Silverstripe413\Rector\Class_\AddManyManyMethodAnnotationsToDataObjectRector\Source\RelationMock[] ManyManyRelationship()
 */
class ManyManyMock extends \SilverStripe\ORM\DataObject implements \SilverStripe\Dev\TestOnly
{
}
