<?php

declare(strict_types=1);

namespace Cambis\SilverstripeRector\ValueObject;

final class SilverstripeConstants
{
    public const PROPERTY_BELONGS_MANY_MANY = 'belongs_many_many';

    public const PROPERTY_BELONGS_TO = 'belongs_to';

    public const PROPERTY_DB = 'db';

    public const PROPERTY_DEPENDENCIES = 'dependencies';

    public const PROPERTY_EXTENSIONS = 'extensions';

    public const PROPERTY_HAS_ONE = 'has_one';

    public const PROPERTY_HAS_MANY = 'has_many';

    public const PROPERTY_MANY_MANY = 'many_many';

    public const PROPERTY_MANY_MANY_EXTRA_FIELDS = 'many_many_extraFields';

    public const PROPERTY_OWNS = 'owns';

    public const METHOD_ADD_FIELD_TO_TAB = 'addFieldToTab';

    public const METHOD_ADD_FIELDS_TO_TAB = 'addFieldsToTab';

    public const METHOD_BY_ID = 'byID';

    public const METHOD_CACHED_CALL = 'cachedCall';

    public const METHOD_CREATE = 'create';

    public const METHOD_EXTEND = 'extend';

    public const METHOD_EXTEND_VALIDATION_RESULT = 'extendValidationResult';

    public const METHOD_GET = 'get';

    public const METHOD_GET_BASE_TAG = 'getBaseTag';

    public const METHOD_GET_BY_ID = 'get_by_id';

    public const METHOD_GET_OWNER = 'getOwner';

    public const METHOD_GET_REQUEST = 'getRequest';

    public const METHOD_GET_SCHEMA_RESPONSE = 'getSchemaResponse';

    public const METHOD_OBJ = 'obj';

    public const METHOD_REMOVE_FIELD_FROM_TAB = 'removeFieldFromTab';

    public const METHOD_REMOVE_FIELDS_FROM_TAB = 'removeFieldsFromTab';

    public const METHOD_UPDATE_VALIDATION_RESULT = 'updateValidationResult';

    /**
     * @var string[]
     * @see https://github.com/emteknetnz/extension-protector/blob/7e778ee94e1b487aeffdd928da39fca037bf1563/metadata.php#L46
     */
    public const PROTECTED_HOOK_METHODS = [
        'afterCallActionHandler',
        'afterCallActionURLHandler',
        'afterCallFormHandler',
        'afterFindOrCreateAdmin',
        'afterFindOrCreateDefaultAdmin',
        'afterGetAllLivePageURLs',
        'afterInsertBaseRows',
        'afterInsertTypeSpecificRows',
        'afterLogin',
        'afterLogout',
        'afterMigrateHasManyRelations',
        'afterMigrateManyManyRelations',
        'afterMigrateTitleColumn',
        'afterPerformMigration',
        'afterPerformReadonlyTransformation',
        'afterSetOwnerForHasOneLinks',
        'afterUpdateFormField',
        'afterUpdateSiteTreeRows',
        'alternateGetByLink',
        'alternateSiteConfig',
        'augmentAllChildrenIncludingDeleted',
        'augmentDataQueryCreation',
        'augmentDatabase',
        'augmentHydrateFields',
        'augmentLoadLazyFields',
        'augmentSQL',
        'augmentStageChildren',
        'augmentSyncLinkTracking',
        'augmentValidURLSegment',
        'augmentWrite',
        'augmentWriteDeletedVersion',
        'authenticationFailedUnknownUser',
        'authenticationSucceeded',
        'beforeCallActionHandler',
        'beforeCallActionURLHandler',
        'beforeCallFormHandler',
        'beforeFindOrCreateAdmin',
        'beforeFindOrCreateDefaultAdmin',
        'beforeGetAllLivePageURLs',
        'beforeInsertBaseRows',
        'beforeInsertTypeSpecificRows',
        'beforeLogin',
        'beforeLogout',
        'beforeMigrateHasManyRelations',
        'beforeMigrateManyManyRelations',
        'beforeMigrateTitleColumn',
        'beforePerformMigration',
        'beforeSetOwnerForHasOneLinks',
        'beforeUpdateFormField',
        'beforeUpdateSiteTreeRows',
        'cacheKeyComponent',
        'canLogIn',
        'contentcontrollerInit',
        'extendCanExecute',
        'failedLogin',
        'failedLogout',
        'getErrorRecordFor',
        'handleAccountReset',
        'memberAutoLoggedIn',
        'migrateHasOneForLinkSubclass',
        'modelascontrollerInit',
        'onActionComplete',
        'onActionStart',
        'onAfterApplyState',
        'onAfterArchive',
        'onAfterChangePassword',
        'onAfterClear',
        'onAfterCopyLocale',
        'onAfterDuplicate',
        'onAfterDuplicateToSubsite',
        'onAfterEndTestSession',
        'onAfterFormSaveInto',
        'onAfterGeneratePageResponse',
        'onAfterGenerateToken',
        'onAfterInit',
        'onAfterLDAPGroupSyncTask',
        'onAfterLDAPMemberSyncTask',
        'onAfterLoad',
        'onAfterLoadIntoFile',
        'onAfterLocalisedCopy',
        'onAfterLocalisedCopyRelation',
        'onAfterParse',
        'onAfterProcessAll',
        'onAfterProcessRecord',
        'onAfterPublish',
        'onAfterPublishRecursive',
        'onAfterRenewToken',
        'onAfterReorderItems',
        'onAfterRequireDefaultElementalRecords',
        'onAfterRestoreToStage',
        'onAfterRevertToLive',
        'onAfterRollbackRecursive',
        'onAfterRollbackSingle',
        'onAfterSave',
        'onAfterSend',
        'onAfterSetPassword',
        'onAfterSkippedWrite',
        'onAfterStartTestSession',
        'onAfterUnpublish',
        'onAfterUpdateTestSession',
        'onAfterUpload',
        'onAfterVersionDelete',
        'onAfterVersionedPublish',
        'onAfterWorkflowPublish',
        'onAfterWorkflowUnublish',
        'onAfterWriteToStage',
        'onBeforeApplyState',
        'onBeforeArchive',
        'onBeforeBuild',
        'onBeforeChangePassword',
        'onBeforeClear',
        'onBeforeCopyLocale',
        'onBeforeDuplicate',
        'onBeforeDuplicateToSubsite',
        'onBeforeEndTestSession',
        'onBeforeFormSaveInto',
        'onBeforeGeneratePageResponse',
        'onBeforeHTTPError',
        'onBeforeInit',
        'onBeforeJSONError',
        'onBeforeLocalisedCopy',
        'onBeforeLocalisedCopyRelation',
        'onBeforeManipulate',
        'onBeforeParse',
        'onBeforeProcessAll',
        'onBeforePublish',
        'onBeforePublishRecursive',
        'onBeforeRemoveLoginSession',
        'onBeforeRender',
        'onBeforeRenderHolder',
        'onBeforeReorderItems',
        'onBeforeRequireDefaultElementalRecords',
        'onBeforeRestoreToStage',
        'onBeforeRevertToLive',
        'onBeforeRollback',
        'onBeforeRollbackRecursive',
        'onBeforeRollbackSingle',
        'onBeforeSaveRequestToStore',
        'onBeforeSecurityLogin',
        'onBeforeSend',
        'onBeforeSetPassword',
        'onBeforeStartTestSession',
        'onBeforeUnpublish',
        'onBeforeUpdateTestSession',
        'onBeforeVersionedPublish',
        'onBeforeWriteToStage',
        'onBulkUpload',
        'onMethodVerificationFailure',
        'onMethodVerificationSuccess',
        'onPopulationFromField',
        'onPrepopulateTreeDataCache',
        'onRealMeLoginFailure',
        'onRealMeLoginSuccess',
        'onRegisterMethod',
        'onRegisterMethodFailure',
        'onSkipRegistration',
        'onTransition',
        'permissionDenied',
        'processHTML',
        'updateAbsoluteLink',
        'updateAfterProcess',
        'updateAlerts',
        'updateAllowedChildren',
        'updateAnchorAndQueryString',
        'updateAnchorsInContent',
        'updateAnchorsOnPage',
        'updateApplyVersionedFiltersAsConditions',
        'updateAttributes',
        'updateAvailableTypesForClass',
        'updateBadge',
        'updateBadgeLabel',
        'updateBadges',
        'updateBaseFields',
        'updateBatchActionsForm',
        'updateBlockSchema',
        'updateBreadcrumbs',
        'updateCMSActions',
        'updateCMSCompositeValidator',
        'updateCMSEditLink',
        'updateCMSTreeTitle',
        'updateCanAttachFileForRecipient',
        'updateCandidateAuthors',
        'updateCandidateUsers',
        'updateChangeSetResource',
        'updateChangeType',
        'updateChangedPasswordEmail',
        'updateCharacterSet',
        'updateCheckForBrokenLinks',
        'updateChildFilter',
        'updateClientConfig',
        'updateClientOptions',
        'updateColumns',
        'updateConfig',
        'updateContentForCmsSearch',
        'updateContentForSearchIndex',
        'updateCurrentPageID',
        'updateCurrentSiteConfig',
        'updateDataSchema',
        'updateDateFormat',
        'updateDefaultFrom',
        'updateDefaultLinkTitle',
        'updateDeleteTable',
        'updateDeleteTables',
        'updateDisownershipQuery',
        'updateDoAdd',
        'updateDropdownFilterOptions',
        'updateEditFormAfter',
        'updateEditLinkForDataObject',
        'updateEmail',
        'updateEmailData',
        'updateErrorFilename',
        'updateExcludedURLSegments',
        'updateExportButton',
        'updateExtraTreeTools',
        'updateFieldLabels',
        'updateFieldValidationOptions',
        'updateFilesInUse',
        'updateFilterDescription',
        'updateFilteredEmailRecipients',
        'updateFluentDirectorDefaultLocale',
        'updateFluentLocales',
        'updateFluentRoutes',
        'updateFluentRoutesForLocale',
        'updateForTemplateDefaultStyles',
        'updateForTemplateTemplate',
        'updateForgotPasswordEmail',
        'updateForm',
        'updateFormActions',
        'updateFormFields',
        'updateFormOptions',
        'updateFormScaffolder',
        'updateFormValidator',
        'updateFormatUrl',
        'updateFrontEndRequiredFields',
        'updateFrontendFormRequirements',
        'updateGeneratedThumbnails',
        'updateGetArchive',
        'updateGetBlogPosts',
        'updateGetData',
        'updateGetOptions',
        'updateGetTypes',
        'updateGetURL',
        'updateGetURLBeforeAnchor',
        'updateGetUrls',
        'updateGetVersionNumberByStage',
        'updateGrant',
        'updateGridField',
        'updateGridFieldConfig',
        'updateGroups',
        'updateGroupsFilter',
        'updateHintsCacheKey',
        'updateHomepageLink',
        'updateHydratedJob',
        'updateImportForm',
        'updateInheritableQueryParams',
        'updateIsArchived',
        'updateIsContributor',
        'updateIsEditor',
        'updateIsMigratable',
        'updateIsOnDraft',
        'updateIsPublished',
        'updateIsSiteUrl',
        'updateIsWriter',
        'updateItemEditForm',
        'updateItemRequestClass',
        'updateItemRequestHandler',
        'updateJobDescriptorAndJobOnCompletion',
        'updateJobDescriptorAndJobOnException',
        'updateJobDescriptorBeforeQueued',
        'updateJobDescriptorOnInitialisationException',
        'updateJoinTableName',
        'updateLinkPageAdd',
        'updateLinkWithSearch',
        'updateList',
        'updateListView',
        'updateLocalePageController',
        'updateLocalisationTabColumns',
        'updateLocalisationTabConfig',
        'updateLocaliseSelect',
        'updateLocaliseSelectDefault',
        'updateLoginAttempt',
        'updateManyManyComponents',
        'updateMemberFormFields',
        'updateMemberPasswordField',
        'updateMetaTitle',
        'updateMigratedElement',
        'updateName',
        'updateNeedsMigration',
        'updateNestedGroupsFilter',
        'updateNewLink',
        'updateNewRowClasses',
        'updateNodesFilter',
        'updateNotifyUsersCMSFields',
        'updateOnMessage',
        'updatePHP',
        'updatePackageInfo',
        'updatePage',
        'updatePageFilter',
        'updatePageOptions',
        'updatePageShouldSkip',
        'updateParameterFields',
        'updatePlaceholderGroups',
        'updatePopoverActions',
        'updatePostURL',
        'updatePrePopulateVersionNumberCache',
        'updatePreviewEnabled',
        'updatePreviewLink',
        'updatePrintData',
        'updatePrintExportColumns',
        'updateProgressForm',
        'updateRandomPassword',
        'updateReceivedFormSubmissionData',
        'updateRecordLocaleStagesDiffer',
        'updateRedirectionLink',
        'updateRenderTemplates',
        'updateRequestURL',
        'updateRequiredFields',
        'updateResetAccountForm',
        'updateResponse',
        'updateRestfulGetHandler',
        'updateRowAttributes',
        'updateRss',
        'updateRules',
        'updateSchema',
        'updateSchemaValidation',
        'updateSearchContext',
        'updateSearchForm',
        'updateSearchableFields',
        'updateSettingsFields',
        'updateShareTokenLink',
        'updateShouldDropColumn',
        'updateShouldMigrateColumn',
        'updateShouldPublishLink',
        'updateShouldPublishLinks',
        'updateSiteTreeAsUL',
        'updateSiteTreeExcludedClassNames',
        'updateSiteTreeHints',
        'updateSourceParams',
        'updateSourceRecords',
        'updateStagesDiffer',
        'updateStartForm',
        'updateStatusFlags',
        'updateStyleVariant',
        'updateSubmissionsGridField',
        'updateSummary',
        'updateSummaryFields',
        'updateTimeFormat',
        'updateTotp',
        'updateTrackedFormUpload',
        'updateTreeTitle',
        'updateURLSegment',
        'updateUsage',
        'updateUsageAncestorDataObjects',
        'updateUsageDataObject',
        'updateUsageExcludedClasses',
        'updateUsersFilter',
        'updateUsersWithIteratorFilter',
        'updateValidTransitions',
        'updateValidatePassword',
        'updateValidationResult',
        'updateValidator',
        'updateVersionModules',
        'updateView',
        'updateWorkflowEditForm',
        'updatelocaliseCondition',
        'updatelocaliseConditionDefault',
        'augmentNewSiteTreeItem',
        'accessedCMS',
        'updateCMSFields',
        'updateFrontEndFields',
        'onAfterDelete',
        'onAfterWrite',
        'onBeforeDelete',
        'onBeforeWrite',
    ];
}
