<?php

namespace Cambis\SilverstripeRector\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Fixture;

/**
 * @template T of \Cambis\SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Source\AnotherBasePage
 * @extends \SilverStripe\CMS\Controllers\ContentController<\Cambis\SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Source\AnotherBasePage>
 */
class AnotherBasePageController extends \SilverStripe\CMS\Controllers\ContentController
{
}
