<?php

namespace SilverstripeRector\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Fixture;

/**
 * @template T of \SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Source\AnotherBasePage
 * @extends \SilverStripe\CMS\Controllers\ContentController<\SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Source\AnotherBasePage>
 */
class AnotherBasePageController extends \SilverStripe\CMS\Controllers\ContentController
{
}
