<?php

namespace SilverstripeRector\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Fixture;

/**
 * @extends \SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Source\BasePageController<\SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Source\CustomPage>
 */
class CustomPageController extends \SilverstripeRector\Tests\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Source\BasePageController
{
}
