<?php

namespace Cambis\SilverstripeRector\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Fixture;

class MissingDataRecordController extends \PageController
{
}

?>
-----
<?php

namespace Cambis\SilverstripeRector\Silverstripe52\Rector\Class_\AddExtendsAnnotationToContentControllerRector\Fixture;

/**
 * @extends \PageController<\Page>
 */
class MissingDataRecordController extends \PageController
{
}

?>
