name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_require_extra: |
        silverstripe/framework:^5.0
        silverstripe/cms:^5.0
        silverstripe/installer:^5.0
      js: false
      simple_matrix: true
